manager-blueprints-url: https://github.com/cloudify-cosmo/cloudify-manager-blueprints/archive/master.tar.gz
cli-package-urls:
  - http://cloudify-release-eu.s3.amazonaws.com/cloudify/4.2.0/ga-release/cloudify-windows-cli_4.2.0-ga.exe
  - http://cloudify-release-eu.s3.amazonaws.com/cloudify/4.2.0/ga-release/cloudify-cli-4.2.0~ga.el6.x86_64.rpm
  - http://cloudify-release-eu.s3.amazonaws.com/cloudify/4.2.0/ga-release/cloudify-cli_4.2.0~ga_amd64.deb
  - http://cloudify-release-eu.s3.amazonaws.com/cloudify/4.2.0/ga-release/cloudify-cli-4.2.0-ga.pkg
mgr-resources-package: http://cloudify-release-eu.s3.amazonaws.com/cloudify/4.2.0/ga-release/cloudify-manager-resources_4.2.0-ga.tar.gz
wagon-files:
  - https://github.com/cloudify-cosmo/cloudify-openstack-plugin/releases/download/2.2.0/cloudify_openstack_plugin-2.2.0-py27-none-linux_x86_64-centos-Core.wgn
  - https://github.com/cloudify-cosmo/cloudify-openstack-plugin/releases/download/2.2.0/cloudify_openstack_plugin-2.2.0-py27-none-linux_x86_64-redhat-Maipo.wgn
  - http://repository.cloudifysource.org/cloudify/wagons/cloudify-vsphere-plugin/2.3.0/cloudify_vsphere_plugin-2.3.0-py27-none-linux_x86_64-centos-Core.wgn
  - http://repository.cloudifysource.org/cloudify/wagons/cloudify-vsphere-plugin/2.3.0/cloudify_vsphere_plugin-2.3.0-py27-none-linux_x86_64-redhat-Maipo.wgn
  - https://github.com/cloudify-incubator/cloudify-awssdk-plugin/releases/download/1.0.0/cloudify_awssdk_plugin-1.0.0-py27-none-any-none-none.wgn
  - https://github.com/cloudify-cosmo/cloudify-aws-plugin/releases/download/1.5.1.2/cloudify_aws_plugin-1.5.1.2-py27-none-linux_x86_64-centos-Core.wgn
  - https://github.com/cloudify-cosmo/cloudify-aws-plugin/releases/download/1.5.1.2/cloudify_aws_plugin-1.5.1.2-py27-none-linux_x86_64-redhat-Maipo.wgn
  - https://github.com/cloudify-cosmo/cloudify-gcp-plugin/releases/download/1.0.1/cloudify_gcp_plugin-1.0.1-py27-none-linux_x86_64-centos-Core.wgn
  - https://github.com/cloudify-incubator/cloudify-azure-plugin/releases/download/1.4.3/cloudify_azure_plugin-1.4.3-py27-none-linux_x86_64.wgn
  - https://github.com/cloudify-incubator/cloudify-kubernetes-plugin/releases/download/1.2.2/cloudify_kubernetes_plugin-1.2.2-py27-none-linux_x86_64.wgn
  - https://github.com/cloudify-cosmo/cloudify-netconf-plugin/releases/download/0.2.0/cloudify_netconf_plugin-0.2.0-py27-none-linux_x86_64-centos-Core.wgn
  - https://github.com/cloudify-incubator/cloudify-utilities-plugin/releases/download/1.3.1/cloudify_utilities_plugin-1.3.1-py27-none-linux_x86_64.wgn
  - https://s3-eu-west-1.amazonaws.com/cloudify-release-eu/cloudify/wagons/cloudify-fabric-plugin/1.5.1/cloudify_fabric_plugin-1.5.1-py27-none-linux_x86_64-centos-Core.wgn
  - https://s3-eu-west-1.amazonaws.com/cloudify-release-eu/cloudify/wagons/cloudify-fabric-plugin/1.5.1/cloudify_fabric_plugin-1.5.1-py27-none-linux_x86_64-redhat-Maipo.wgn
  - http://repository.cloudifysource.org/cloudify/wagons/cloudify-diamond-plugin/1.3.6/cloudify_diamond_plugin-1.3.6-py26-none-linux_x86_64-centos-Final.wgn
  - http://repository.cloudifysource.org/cloudify/wagons/cloudify-diamond-plugin/1.3.6/cloudify_diamond_plugin-1.3.6-py27-none-linux_x86_64-Ubuntu-trusty.wgn
  - http://repository.cloudifysource.org/cloudify/wagons/cloudify-diamond-plugin/1.3.6/cloudify_diamond_plugin-1.3.6-py27-none-linux_x86_64-redhat-Maipo.wgn
  - http://repository.cloudifysource.org/cloudify/wagons/cloudify-docker-plugin/1.3.2/cloudify_docker_plugin-1.3.2-py27-none-linux_x86_64-centos-Core.wgn
  - http://repository.cloudifysource.org/cloudify/wagons/cloudify-docker-plugin/1.3.2/cloudify_docker_plugin-1.3.2-py27-none-linux_x86_64-Ubuntu-trusty.wgn
  - http://repository.cloudifysource.org/cloudify/wagons/cloudify-psutil-plugin/1.0.2/cloudify_psutil_plugin-1.0.2-py27-none-win32-none-none.wgn
  - http://repository.cloudifysource.org/cloudify/wagons/cloudify-host-pool-plugin/1.5/cloudify_host_pool_plugin-1.5-py27-none-linux_x86_64-centos-Core.wgn
# These are DSL resources that we want to have available on the manager,
# in addition to the ones that are copied automatically by the bootstrap process.
extra-dsl-resources:
  - http://cloudify.co/spec/openstack-plugin/2.2.0/plugin.yaml
  - http://cloudify.co/spec/vsphere-plugin/2.3.0/plugin.yaml
  - https://raw.githubusercontent.com/cloudify-incubator/cloudify-awssdk-plugin/master/plugin.yaml
  - https://raw.githubusercontent.com/cloudify-cosmo/cloudify-aws-plugin/1.5.1.2/plugin.yaml
  - https://raw.githubusercontent.com/cloudify-cosmo/cloudify-gcp-plugin/1.0.1/plugin.yaml
  - https://raw.githubusercontent.com/cloudify-incubator/cloudify-azure-plugin/1.4.3/plugin.yaml
  - https://raw.githubusercontent.com/cloudify-incubator/cloudify-kubernetes-plugin/1.2.2/plugin.yaml
  - https://raw.githubusercontent.com/cloudify-cosmo/cloudify-netconf-plugin/0.2.0/plugin.yaml
  - https://raw.githubusercontent.com/cloudify-incubator/cloudify-utilities-plugin/1.3.1/plugin.yaml
  - https://raw.githubusercontent.com/cloudify-cosmo/cloudify-fabric-plugin/1.5.1/plugin.yaml
  - http://cloudify.co/spec/docker-plugin/1.3.2/plugin.yaml
  - http://cloudify.co/spec/psutil-plugin/1.0.2/plugin.yaml
  - http://cloudify.co/spec/host-pool-plugin/1.5/plugin.yaml