editions:
  community:
    manager-blueprints-url: https://github.com/cloudify-cosmo/cloudify-manager-blueprints/archive/17.11.22.tar.gz
    cli-package-urls:
      - http://repository.cloudifysource.org/cloudify/17.11.22/community-release/cloudify-cli-community-17.11.22.exe
      - http://repository.cloudifysource.org/cloudify/17.11.22/community-release/cloudify-cli-community-17.11.22.rpm
      - http://repository.cloudifysource.org/cloudify/17.11.22/community-release/cloudify-cli-community-17.11.22.deb
      - http://repository.cloudifysource.org/cloudify/17.11.22/community-release/cloudify-cli-community-17.11.22.pkg
    mgr-resources-package: http://repository.cloudifysource.org/cloudify/17.11.22/community-release/cloudify-manager-resources-community-17.11.22.tar.gz
  premium:
    manager-blueprints-url: https://github.com/cloudify-cosmo/cloudify-manager-blueprints/archive/4.2.tar.gz
    cli-package-urls:
      - http://repository.cloudifysource.org/cloudify/4.2.0/ga-release/cloudify-cli-4.2ga.exe
      - http://repository.cloudifysource.org/cloudify/4.2.0/ga-release/cloudify-cli-4.2ga.rpm
      - http://repository.cloudifysource.org/cloudify/4.2.0/ga-release/cloudify-cli-4.2ga.deb
      - http://repository.cloudifysource.org/cloudify/4.2.0/ga-release/cloudify-cli-4.2ga.pkg
    mgr-resources-package: http://repository.cloudifysource.org/cloudify/4.2.0/ga-release/cloudify-manager-resources-4.2ga.tar.gz
python-prereq-rpms:
  - http://mirror.centos.org/centos/7/os/x86_64/Packages/python-backports-1.0-8.el7.x86_64.rpm
  - http://mirror.centos.org/centos/7/os/x86_64/Packages/python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch.rpm
  - http://mirror.centos.org/centos/7/os/x86_64/Packages/python-setuptools-0.9.8-7.el7.noarch.rpm
plugins:
  # AWS 1.5.1.2
  - dsl: http://www.getcloudify.org/spec/aws-plugin/1.5.1.2/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-aws-plugin/1.5.1.2/cloudify_aws_plugin-1.5.1.2-py27-none-linux_x86_64-centos-Core.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-aws-plugin/1.5.1.2/cloudify_aws_plugin-1.5.1.2-py27-none-linux_x86_64-redhat-Maipo.wgn
  # AWS SDK 1.2.0.1
  - dsl: http://www.getcloudify.org/spec/awssdk-plugin/1.2.0.1/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-awssdk-plugin/1.2.0.1/cloudify_awssdk_plugin-1.2.0.1-py27-none-linux_x86_64-centos-Core.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-awssdk-plugin/1.2.0.1/cloudify_awssdk_plugin-1.2.0.1-py27-none-linux_x86_64-redhat-Maipo.wgn
  # Azure 1.4.3
  - dsl: http://www.getcloudify.org/spec/azure-plugin/1.4.3/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-azure-plugin/1.4.3/cloudify_azure_plugin-1.4.3-py27-none-linux_x86_64.wgn
  # Diamond 1.3.6
  - dsl: http://www.getcloudify.org/spec/diamond-plugin/1.3.6/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-diamond-plugin/1.3.6/cloudify_diamond_plugin-1.3.6-py26-none-linux_x86_64-centos-Final.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-diamond-plugin/1.3.6/cloudify_diamond_plugin-1.3.6-py27-none-linux_x86_64-Ubuntu-trusty.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-diamond-plugin/1.3.6/cloudify_diamond_plugin-1.3.6-py27-none-linux_x86_64-redhat-Maipo.wgn
  # Fabric 1.5.1
  - dsl: http://www.getcloudify.org/spec/fabric-plugin/1.5.1/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-fabric-plugin/1.5.1/cloudify_fabric_plugin-1.5.1-py27-none-linux_x86_64-centos-Core.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-fabric-plugin/1.5.1/cloudify_fabric_plugin-1.5.1-py27-none-linux_x86_64-redhat-Maipo.wgn
  # GCP 1.3.0.1
  - dsl: http://www.getcloudify.org/spec/gcp-plugin/1.3.0.1/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-gcp-plugin/1.3.0.1/cloudify_gcp_plugin-1.3.0.1-py27-none-linux_x86_64-centos-Core.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-gcp-plugin/1.3.0.1/cloudify_gcp_plugin-1.3.0.1-py27-none-linux_x86_64-redhat-Maipo.wgn
  # Host Pool 1.5
  - dsl: http://www.getcloudify.org/spec/host-pool-plugin/1.5/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-host-pool-plugin/1.5/cloudify_host_pool_plugin-1.5-py27-none-linux_x86_64-centos-Core.wgn
  # Kubernetes 2.0.0
  - dsl: http://www.getcloudify.org/spec/kubernetes-plugin/2.0.0/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-kubernetes-plugin/2.0.0/cloudify_kubernetes_plugin-2.0.0-py27-none-linux_x86_64-centos-Core.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-kubernetes-plugin/2.0.0/cloudify_kubernetes_plugin-2.0.0-py27-none-linux_x86_64-redhat-Maipo.wgn
  # Netconf 0.2.0
  - dsl: http://www.getcloudify.org/spec/netconf-plugin/0.2.0/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-netconf-plugin/0.2.0/cloudify_netconf_plugin-0.2.0-py27-none-linux_x86_64-centos-Core.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-netconf-plugin/0.2.0/cloudify_netconf_plugin-0.2.0-py27-none-linux_x86_64-redhat-Maipo.wgn
  # NSX 1.1
  - dsl: http://www.getcloudify.org/spec/nsx-plugin/1.1/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-nsx-plugin/1.1/cloudify_nsx_plugin-1.1-py27-none-linux_x86_64.wgn
  # OpenStack 2.5.0
  - dsl: http://www.getcloudify.org/spec/openstack-plugin/2.5.0/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-openstack-plugin/2.5.0/cloudify_openstack_plugin-2.5.0-py27-none-linux_x86_64-centos-Core.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-openstack-plugin/2.5.0/cloudify_openstack_plugin-2.5.0-py27-none-linux_x86_64-redhat-Maipo.wgn
  # PSUtil 1.0.2
  - dsl: http://www.getcloudify.org/spec/psutil-plugin/1.0.2/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-psutil-plugin/1.0.2/cloudify_psutil_plugin-1.0.2-py27-none-linux_x86_64.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-psutil-plugin/1.0.2/cloudify_psutil_plugin-1.0.2-py27-none-win32-none-none.wgn
  # Utilities 1.4.2.1
  - dsl: http://www.getcloudify.org/spec/utilities-plugin/1.4.2.1/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-utilities-plugin/1.4.2.1/cloudify_utilities_plugin-1.4.2.1-py27-none-linux_x86_64-centos-Core.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-utilities-plugin/1.4.2.1/cloudify_utilities_plugin-1.4.2.1-py27-none-linux_x86_64-redhat-Maipo.wgn
  # vSphere 2.3.0
  - dsl: http://www.getcloudify.org/spec/vsphere-plugin/2.3.0/plugin.yaml
    wagons:
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-vsphere-plugin/2.3.0/cloudify_vsphere_plugin-2.3.0-py27-none-linux_x86_64-centos-Core.wgn
      - http://repository.cloudifysource.org/cloudify/wagons/cloudify-vsphere-plugin/2.3.0/cloudify_vsphere_plugin-2.3.0-py27-none-linux_x86_64-redhat-Maipo.wgn
